name: nodejs

type: nodejs:10

relationships:
  headless: "headless:http"

crons:
  cleanup:
    spec: '*/30 * * * *'
    cmd: rm pdfs/*

web:
  commands:
    start: "nodejs index.js"

mounts:
  "/run": "shared:files/run"
  "/screenshots": "shared:files/screenshots"
  "/pdfs": "shared:files/pdfs"

disk: 512