name: nodejs

type: nodejs:10

relationships:
  headless: "headless:http"

crons:
  cleanup:
    spec: '*/30 * * * *'
    cmd: rm pdfs/* && rm screenshots/*

web:
  commands:
    start: "node index.js"

mounts:
  "/pdfs": "shared:files/pdfs"
  "/screenshots": "shared:files/screenshots"

disk: 512